### ISSUE TITLE
Feedback and patch for byacc under Windows commandline

### ISSUE THREAD

**Issue by BeErikk** [ThomasDickey/byacc-snapshots#1]
Thank you Thomas Dickey for a piece of beautiful code.

I first compiled byacc a couple of years ago for Interix, where it compiled right out of the box and could replace the incompatible and cumbersome bison. Somewhat of a sensation to me at the time. Now Interix is no more and I'm trying to get a couple of tools working for the Windows commandline.  

When it comes to byacc, it appears the biggest difference between the various "unix" environments in Windows (Interix, Cygwin etc) and Windows commandline, is the presence of the `TMPDIR` environment variable. In my experience a proper path for temporary files is needed by byacc under Windows commandline, otherwise there's a risk of empty files. The `TEMP` environment variable is always defined in Windows and can easily replace the `TMPDIR` environment variable.

I also made a quick fix for the `noreturn` attribute.

[byacc-msvcrt.patch.txt](https://github.com/ThomasDickey/byacc-snapshots/files/1528165/byacc-msvcrt.patch.txt)

Some additional definitions needed for MSVCRT (from my Interix tree):
```
/* POSIX const for MSVCRT access */
enum _access_const
{
    F_OK            = 00,   /* Test for existence of file */
/*  X_OK            = 01,*/ /* Test for execute (search) permission */
    W_OK            = 02,   /* Test for write permission */
    R_OK            = 04,   /* Test for read permission */
    RW_OK           = 06    /* Test for read and write permission */
};
typedef int32_t mode_t;
```
and for completeness my config.h settings

```
#ifndef HAVE_FCNTL_H
#define HAVE_FCNTL_H 1
#endif
#ifndef HAVE_VSNPRINTF
#define HAVE_VSNPRINTF 1
#endif

/* Define to maximum table size (default: 32500) */
#ifndef MAXTABLE
#define MAXTABLE INT_MAX
#endif

/* Define to 1 to enable backtracking extension */
#ifndef YYBTYACC
#define YYBTYACC 1
#endif

/* Define to 1 if you want to perform memory-leak testing. */
#if defined(_DEBUG) && !defined(YY_NO_LEAKS) 
#define YY_NO_LEAKS 1
#endif
```

**Comment by ThomasDickey** [comment]
thanks.  I'll adapt these changes (there's also P_tmpdir to consider).

**Comment by ThomasDickey** [comment]
done in [2017-12-04](https://invisible-island.net/byacc/CHANGES.html#t20171204)
